### ISSUE TITLE
Typescript errors

### ISSUE THREAD

**Issue by bugleev** [dai-shi/react-hooks-async#34] opened 2019-11-26 13:20 UTC
When running typescript app, errors are shown in response from useAsyncTaskFetch because of unknown[] types.
See: [Codesandbox](https://codesandbox.io/s/admiring-shtern-s48jg).
Is there issue with typings or am I doing something wrong?

**Comment by dai-shi** [comment] 2019-11-26 13:40
Hi, thanks for reporting.
Here's the fix: https://codesandbox.io/s/dazzling-forest-jk9i3
Does this work for you?

So, I guess the issue is the lack of documentation for TypeScript users. 😓

**Comment by bugleev** [comment] 2019-11-26 13:56
> Does this work for you?

Yes, that's perfect. 

> So, I guess the issue is the lack of documentation for TypeScript users

Don't know, maybe things like that are obvious to experienced Typescript users, I'm just not yet one of them 🤔

**Comment by dai-shi** [comment] 2019-11-26 14:15
Good. Anyway, I think it would be nice to have documentation improved some more.

Closing this issue. Feel free to ask questions here or open a new issue.

(BTW, I found a typing issue with regard to this issue. Fixed by e7db084.)

**Closed by dai-shi** 2019-11-26 14:15 UTC
